default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local: &local
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  <<: *local
  database: project_development

test:
  <<: *default
  <<: *local
  database: project_test

production:
  <<: *default
  <<: *local
  database: project_production
  # url: TBD (<%= ENV['DATABASE_URL'] %>)
