version: "3"

services:
  db:
    platform: linux/x86_64
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      TZ: "Asia/Tokyo"
    user: postgres

  frontend:
    build:
      context: ./frontend
    command: sh -c "yarn && yarn dev"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
volumes:
  postgres:
  frontend:
